### ISSUE TITLE
Couple of things

### ISSUE THREAD

**Issue by EmanMac** [mannd00/week4#2]
The easy fix I see is you did "unmount" instead of "umount" at the end there.
I didn't get the hexdump at the end to work using "--canonical" and got an error, but -c seemed to at least do something for me.
Tried changing that and I still get caught up on the mkfs command, says the command is not found. I haven't managed to solve this issue myself so if you can get it to work would love to know what you did.

**Comment by mannd00** [comment]
Fixed typo, and changed to "-c" for hexdump command. Looks like mkfs needed to use sudo to run.

Thanks for the feedback!
